### ISSUE TITLE
How to use pre-trained simplification models?

### ISSUE THREAD

**Issue by MiriUll** [rstodden/DEPlain#1]
I try to recreate your results on the DEplain-web-sent dataset with the models from Huggingface but it seems I am using the wrong decoding strategy. Can you share more details on how you created these model outputs in [this folder](https://github.com/rstodden/DEPlain/blob/main/G__Automatic_Text_Simplification_Experiments/generated_outputs/sentence-level/trimmed_mbart_35k_on_APA-web/tested_on_DEplain-web)?

I used the [trimmed_mbart_sents_apa_web](https://huggingface.co/DEplain/trimmed_mbart_sents_apa_web) model and tried different strategies:
![image](https://github.com/rstodden/DEPlain/assets/26796274/da8d4c4e-2461-4ff2-b5a2-6d734f40af45)

Thanks for your help!

**Comment by OmarMomen14** [comment]
Hi,

Thank you for your question.

We used beam search as our decoding strategy, with num_beams = 6.

But we've just figured out that the checkpoint file at the HuggingFace model page is NOT the one that was used to get our published results. We fixed that mistake and now the correct checkpoint is updated on HF.

Kindly try again using our decoding strategy, and let us know if you are still facing any problems :slightly_smiling_face:

**Comment by MiriUll** [comment]
Hi, 
thank you very much for your quick answer! I can now recreate the example outputs. Anyways, the decoding strategy does not make a big difference now.

**Comment by OmarMomen14** [comment]
You are welcome!

Actually, we haven't tested with different decoding strategies, we just used the default setting. Because the primary goal of our experiment was just to show a use case example for our proposed dataset `DEplain`.
But thanks for reporting that.
